import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from '@/components/text-navbar';
import { Footer } from '@/components/footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full">
      <body className="h-full">
        <div className="min-h-full flex flex-col">
          {/* Header */}
          <header className="bg-gray-800 text-white">
            <Navbar />
          </header>

          {/* Main content that takes remaining space */}
          <main className="flex-1 relative">{children}</main>

          {/* Footer */}
          <footer className="bg-gray-800 text-white p-4 mt-auto">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
